/*
* This source file was generated by the csv2binary program that developed by Andi Hasan A
* Do not delete this note! (Jangan hapus catatan ini!)
*
* @github https://github.com/hasanelfalakiy
*/

package com.andihasan7.lib.vsop87d.elpmpp02.moonterms

object MOON_R3 {
   val moon_R3 = arrayOf(
       doubleArrayOf(6.13564401E-7,-21.7363659563692,8326.390224682,3.04584815524652E-4,5.01437748309309E-7,-2.4719679972413E-9),
       doubleArrayOf(5.75594986E-7,32.7305032177683,8330.9926245649,0.0,0.0,0.0)
   )
}