/*
 * This source file was generated by the Gradle 'init' task
 */
 
 /**
 * This file is part of lib-vsop87d-elpmpp02.
 *
 * lib-vsop87d-elpmpp02 is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * lib-vsop87d-elpmpp02 is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with lib-vsop87d-elpmpp02.  If not, see <https://www.gnu.org/licenses/>.
 *
 *
 * @programmed by: Andi Hasan A
 * @github: https://github.com/hasanelfalakiy
 * 
 *
 */
 
package com.andihasan7.lib.vsop87d.elpmpp02

import kotlin.test.Test
import com.andihasan7.lib.vsop87d.elpmpp02.VSOP87DELPMPP02
import com.andihasan7.lib.vsop87d.elpmpp02.convertutil.ConvertUtil


class LibraryTest {

    
    @Test
    fun positionTest() {
    
        val ephe = VSOP87DELPMPP02(
            date = 20,
            month = 4,
            year = 2023,
            latitude = -7.029055555556,
            longitude = 106.557722222222,
            elevation = 52.685,
            timeZone = 7.0,
            hourDouble = 17.8575,
            checkDeltaT = true
        )
        
        val cv = ConvertUtil
        
        val jd = ephe.jd
        val deltaT = ephe.deltaT
        val jde = ephe.jde
        val jc = ephe.jc
        val jce = ephe.jce
        val jm = ephe.jm
        val jme = ephe.jme
        val hourDouble = (ephe.hourDouble) // use ?. for casting to other data type
        val nutationInLongitude = ephe.nutationInLongitude
        val nutationInObliquity = ephe.nutationInObliquity
        val meanObliquityOfEcliptic = ephe.meanObliquityOfEcliptic
        val trueObliquityOfEcliptic = ephe.trueObliquityOfEcliptic
        val earthHelioLon = ephe.earthHeliocentricLongitudeDegree
        val earthHelioLat = ephe.earthHeliocentricLatitudeDegree
        val sunTrueGeoLon = ephe.sunTrueGeocentricLongitude
        val sunTrueGeoLat = ephe.sunTrueGeocentricLatitude
        val abr = ephe.abr
        val sunAppaGeoLon = ephe.sunApparentGeocentricLongitude
        val sunGeoDistanceAU = ephe.sunGeocentricDistanceAU
        val sunGeoDistanceKM = ephe.sunGeocentricDistanceKM
        val sunGeoDistanceER = ephe.sunGeocentricDistanceER
        val sunAppaGeoSemidiameter = ephe.sunApparentGeoSemidiameter
        val sunAppaGeoRA = ephe.sunApparentGeoRightAscension
        val sunAppaGeoDec = ephe.sunApparentGeoDeclination
        val gmst = ephe.greenwichMeanSiderealTime
        val gast = ephe.greenwichApparentSiderealTime
        val last = ephe.localApparentSiderealTime
        val gha = ephe.sunGeoGreenwichHourAngle
        val lha = ephe.sunGeoLocalHourAngle
        val sunGeoAzimuth = ephe.sunGeoAzimuth
        val sunGeoAltitude = ephe.sunGeoAltitude
        
        println("Ephemeris VSOP87D & ELPMPP02 Full Periodic Terms (38.326)")
        println("")
        println("this is unit test")
        println("")
        println("Number of Date: ${ephe.numbDate}")
        println("Number of Month: ${ephe.numbMonth}")
        println("Name of Month: ${ephe.nameMonth}")
        println("Number of Year: ${ephe.numbYear}")
        println("Number of Day: ${ephe.numbDay}")
        println("Name of Day: ${ephe.nameDay}")
        println("Number of Pasaran: ${ephe.numbPasaran}")
        println("Name of Pasaran: ${ephe.namePasaran}")
        println("Hour Decimal: $hourDouble")
        println("Frac of Day: ${ephe.fracDay}")
        println("")
        println("Julian Day: $jd")
        println("Delta T: $deltaT")
        println("JDE: $jde")
        println("JC: $jc")
        println("JCE: $jce")
        println("JM: $jm")
        println("JME: $jme")
        println("Nutation in Lon: $nutationInLongitude, ${cv.toDegreeFullRound2(nutationInLongitude)}")
        println("Nutation in Obli: $nutationInObliquity, ${cv.toDegreeFullRound2(nutationInObliquity)}")
        println("Mean Obliquity: $meanObliquityOfEcliptic, ${cv.toDegreeFullRound2(meanObliquityOfEcliptic)}")
        println("True Obliquity: $trueObliquityOfEcliptic, ${cv.toDegreeFullRound2(trueObliquityOfEcliptic)}")
        println("")
        println("Earth Helio Lon: $earthHelioLon, ${cv.toDegreeFullRound2(earthHelioLon)}")
        println("Earth Helio Lat: $earthHelioLat, ${cv.toDegreeFullRound2(earthHelioLat)}")
        println("")
        println("Sun Geocentric Coor:")
        println("")
        println("Sun True Geo Lon: $sunTrueGeoLon, ${cv.toDegreeFullRound2(sunTrueGeoLon)}")
        println("Sun True Geo Lat: $sunTrueGeoLat, ${cv.toDegreeFullRound2(sunTrueGeoLat)}")
        println("Abration: $abr, ${cv.toDegreeFullRound2(abr)}")
        println("Sun Appa Geo Lon: $sunAppaGeoLon, ${cv.toDegreeFullRound2(sunAppaGeoLon)}")
        println("Sun Geo Distance AU: $sunGeoDistanceAU")
        println("Sun Geo Distance KM: $sunGeoDistanceKM")
        println("Sun Geo Distance ER: $sunGeoDistanceER")
        println("Sun Appa Geo Semidiameter: $sunAppaGeoSemidiameter, ${cv.toDegreeFullRound2(sunAppaGeoSemidiameter)}")
        println("Sun Appa Geo Right Ascen: $sunAppaGeoRA, ${cv.toDegreeFullRound2(sunAppaGeoRA)}")
        println("Sun Appa Geo Declination: $sunAppaGeoDec, ${cv.toDegreeFullRound2(sunAppaGeoDec)}")
        println("Greenwich Mean Sidereal Time: $gmst")
        println("Greenwich Apparent Sidereal Time: $gast")
        println("Local Apparent Sidereal Time: $last")
        println("Sun Geo Greenwich HA: $gha, ${cv.toDegreeFullRound2(gha)}")
        println("Sun Geo Local HA: $lha, ${cv.toDegreeFullRound2(lha)}")
        println("Sun Geo Azimuth: $sunGeoAzimuth, ${cv.toDegreeFullRound2(sunGeoAzimuth)}")
        println("Sun Geo Altitude: $sunGeoAltitude, ${cv.toDegreeFullRound2(sunGeoAltitude)}")
        println("")
        println("Sun Topocentric Coor:")
        println("")
        
    }
    
}
