/*
* This source file was generated by the csv2binary program that developed by Andi Hasan A
* Do not delete this note! (Jangan hapus catatan ini!)
*
* @github https://github.com/hasanelfalakiy
*/

package com.andihasan7.lib.vsop87d.elpmpp02.earthterms

object EARTH_R5 {
   val earth_R5 = arrayOf(
       doubleArrayOf(8.6E-10,1.21579741687,6283.0758499914),
       doubleArrayOf(1.2E-10,0.65617264033,12566.1516999828),
       doubleArrayOf(1.0E-11,0.38068797142,18849.2275499742)
   )
}